field: 1bf489cc-2fd1-4e7e-baa4-95efe35f3bba # Content Blocks
fieldLayouts:
  ba0a1dc1-5c0a-4e91-8af0-34663cb049ca:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 575b3c65-6c06-41b4-936e-2ecbfa62f98f # Block Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c5cbe3f-fd96-4b04-a7e2-dcd8b8727731
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 977d3d7e-9e94-4891-ba28-2ad4a186037c # خلفية العنوان
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d859bf93-bee8-45d8-bd67-a24a58de293b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 32457659-ebbf-4d1a-b8a1-c3c8b2f743dc # توسيط العنوان
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f3f9504-393a-4f79-84ba-4660b9259a13
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 25289516-66ff-478a-8006-fd9b33a1c501 # Block Title Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f4fb039-1e2b-4bfc-97e8-c715e0a77fb9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4d81160e-0a7f-4404-90c6-1b4bf2564942 # Block Title Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc9a38a9-4fc4-42f0-8729-29a4a2f09a7a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f70ff4bc-7fbb-4b46-8c9d-efb34d6edff9 # Block Title Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d87ab90f-8dac-45e5-9852-771cf0756891
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 49317fef-5681-42b7-a24d-d3aa39e98cd8 # لون الخلفية
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 499bc0d7-d466-439b-a4a7-b0ce8ae963ea
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 139d5f16-59e0-472d-aabc-d54efec291ec # Block Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3aa3b3a6-5bac-4d4e-85de-0842c4b58670
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c549e248-ce30-4eaf-a389-a682aecb8cf7 # رابط التحميل
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 15209657-f8c0-470c-87e6-8909caa1bbd1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5e085c16-b1dc-4673-a4a3-8246f5e8989e # لون الايقونة
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dfd98240-86a7-476f-a763-abfbf7e253e9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f987f327-53f8-427f-926f-cd7407eb5c2f # حجم الايقونة
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a165898b-7770-4ffc-b216-7f0d8c782e8c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f5e44217-568c-40d8-af8c-98fc47f226c7 # all Link Nofollow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 026d675b-0726-44df-b9a0-36875a24444d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e20083f1-ec80-4f2a-b540-695a91e6673f # alt Title From Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f810a24-82d4-46a0-83c5-1e7735f97865
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7be15c83-fd6e-4e13-a086-d655e9aa367a
        userCondition: null
fields:
  4d81160e-0a7f-4404-90c6-1b4bf2564942: # Block Title Color
    columnSuffix: uowfxkvy
    contentColumnType: char(7)
    fieldGroup: null
    handle: blockTitleColor
    instructions: null
    name: 'Block Title Color'
    searchable: true
    settings:
      defaultColor: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Color
  5e085c16-b1dc-4673-a4a3-8246f5e8989e: # لون الايقونة
    columnSuffix: lqfelnys
    contentColumnType: char(7)
    fieldGroup: null
    handle: lonAlaykon
    instructions: null
    name: 'لون الايقونة'
    searchable: true
    settings:
      defaultColor: '#000000'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Color
  139d5f16-59e0-472d-aabc-d54efec291ec: # Block Content
    columnSuffix: lcsnfahc
    contentColumnType: mediumtext
    fieldGroup: null
    handle: blockContent
    instructions: null
    name: 'Block Content'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: mediumtext
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: false
      redactorConfig: Standard.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: true
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  575b3c65-6c06-41b4-936e-2ecbfa62f98f: # Block Title
    columnSuffix: ybpixmzp
    contentColumnType: text
    fieldGroup: null
    handle: blockTitle
    instructions: null
    name: 'Block Title'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  977d3d7e-9e94-4891-ba28-2ad4a186037c: # خلفية العنوان
    columnSuffix: zdjqqofr
    contentColumnType: string
    fieldGroup: null
    handle: khlfyAlaanoan
    instructions: null
    name: 'خلفية العنوان'
    searchable: true
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - def
            -
              - value
              - def
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - success
            -
              - value
              - success
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - info
            -
              - value
              - info
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - custom
            -
              - value
              - custom
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - golden
            -
              - value
              - golden
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  49317fef-5681-42b7-a24d-d3aa39e98cd8: # لون الخلفية
    columnSuffix: fnmetnfa
    contentColumnType: char(7)
    fieldGroup: null
    handle: lonAlkhlfy
    instructions: null
    name: 'لون الخلفية'
    searchable: true
    settings:
      defaultColor: '#ffffff'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Color
  25289516-66ff-478a-8006-fd9b33a1c501: # Block Title Type
    columnSuffix: lreznuwy
    contentColumnType: string
    fieldGroup: null
    handle: blockTitleType
    instructions: null
    name: 'Block Title Type'
    searchable: true
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - h2
            -
              - value
              - h2
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - h3
            -
              - value
              - h3
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - h4
            -
              - value
              - h4
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - h5
            -
              - value
              - h5
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - h6
            -
              - value
              - h6
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  32457659-ebbf-4d1a-b8a1-c3c8b2f743dc: # توسيط العنوان
    columnSuffix: navybjnm
    contentColumnType: boolean
    fieldGroup: null
    handle: tosytAlaanoan
    instructions: null
    name: 'توسيط العنوان'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  c549e248-ce30-4eaf-a389-a682aecb8cf7: # رابط التحميل
    columnSuffix: vbtaongh
    contentColumnType: text
    fieldGroup: null
    handle: rabtAlthmyl
    instructions: null
    name: 'رابط التحميل'
    searchable: true
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - 'نص الرابط'
                -
                  - handle
                  - nsAlrabt
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - الرابط
                -
                  - handle
                  - alrabt
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col3
            -
              __assoc__:
                -
                  - heading
                  - 'لون الرابط'
                -
                  - handle
                  - lonAlrabt
                -
                  - width
                  - ''
                -
                  - type
                  - color
          -
            - col4
            -
              __assoc__:
                -
                  - heading
                  - 'لون الخلفية'
                -
                  - handle
                  - lonAlkhlfy
                -
                  - width
                  - ''
                -
                  - type
                  - color
          -
            - col5
            -
              __assoc__:
                -
                  - heading
                  - 'حجم الرابط'
                -
                  - handle
                  - hgmAlrabt
                -
                  - width
                  - ''
                -
                  - type
                  - select
                -
                  - options
                  -
                    -
                      __assoc__:
                        -
                          - label
                          - كبير
                        -
                          - value
                          - kbyr
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - وسط
                        -
                          - value
                          - ost
                        -
                          - default
                          - true
                    -
                      __assoc__:
                        -
                          - label
                          - صغير
                        -
                          - value
                          - sghyr
                        -
                          - default
                          - false
          -
            - col6
            -
              __assoc__:
                -
                  - heading
                  - nofollow
                -
                  - handle
                  - nofollow
                -
                  - width
                  - ''
                -
                  - type
                  - lightswitch
          -
            - col7
            -
              __assoc__:
                -
                  - heading
                  - 'تفعيل العداد'
                -
                  - handle
                  - tfaaylAlaadad
                -
                  - width
                  - ''
                -
                  - type
                  - lightswitch
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
            -
              - col3
              - '000'
            -
              - col4
              - ''
            -
              - col5
              - kbyr
            -
              - col6
              - ''
            -
              - col7
              - ''
      maxRows: null
      minRows: null
      staticRows: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  e20083f1-ec80-4f2a-b540-695a91e6673f: # alt Title From Image
    columnSuffix: gwblbcjy
    contentColumnType: boolean
    fieldGroup: null
    handle: altTitleFromImage
    instructions: null
    name: 'alt Title From Image'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  f5e44217-568c-40d8-af8c-98fc47f226c7: # all Link Nofollow
    columnSuffix: lzwnurwn
    contentColumnType: boolean
    fieldGroup: null
    handle: allLinkNofollow
    instructions: null
    name: 'all Link Nofollow'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  f70ff4bc-7fbb-4b46-8c9d-efb34d6edff9: # Block Title Background Color
    columnSuffix: qzuygqfj
    contentColumnType: char(7)
    fieldGroup: null
    handle: blockTitleBackgroundColor
    instructions: null
    name: 'Block Title Background Color'
    searchable: true
    settings:
      defaultColor: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Color
  f987f327-53f8-427f-926f-cd7407eb5c2f: # حجم الايقونة
    columnSuffix: eytaamad
    contentColumnType: text
    fieldGroup: null
    handle: hgmAlaykon
    instructions: null
    name: 'حجم الايقونة'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: block
name: Block
sortOrder: 1
