field: 1bf489cc-2fd1-4e7e-baa4-95efe35f3bba # Content Blocks
fieldLayouts:
  3c6d230c-c4af-4864-a6da-3df8f3b87366:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 698e08c2-cb79-4da2-8c8b-6ce4f1a8a137 # Quiz
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc6516c1-344d-4cf7-8744-88f561808091
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a16bb3c4-d2dc-4c51-acf1-bc2e5ad675d2 # Answer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 485e004e-eb40-4bc6-a782-4ae0a00a86a4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 92c778ef-711b-4ec8-bb2c-76c2f9214aa7 # Quiz Table
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aec5e7ad-097d-44f3-80b6-2034f5cb9f0f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0d79d8dd-ed45-4ba1-bb78-339c88995c85
        userCondition: null
fields:
  92c778ef-711b-4ec8-bb2c-76c2f9214aa7: # Quiz Table
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: quizTable
    instructions: null
    name: 'Quiz Table'
    searchable: true
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 967920641
      columns:
        __assoc__:
          -
            - 3a7067c4-4ab8-45e1-b5b9-61c1aa6431ee
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - e394587c-1d29-4cfe-907f-7d8e1aee9950
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_quiztable}}'
      fieldLayout: matrix
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
  698e08c2-cb79-4da2-8c8b-6ce4f1a8a137: # Quiz
    columnSuffix: wwqizdgg
    contentColumnType: text
    fieldGroup: null
    handle: quiz
    instructions: null
    name: Quiz
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a16bb3c4-d2dc-4c51-acf1-bc2e5ad675d2: # Answer
    columnSuffix: htqzpopg
    contentColumnType: text
    fieldGroup: null
    handle: answer
    instructions: null
    name: Answer
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: faqs
name: Faqs
sortOrder: 4
