field: ab15395e-7128-4aeb-9990-25e8933388c3 # App Gallery links
fieldLayouts:
  deab3845-9cd7-41fd-9b5d-dd014593f328:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5f37a37b-d287-46e1-ab4c-0b7f707fa5ab # Image Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 346c3fe6-2eb0-4704-84e5-9d3bc7a6ab19
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 81ff6b83-9a33-4da4-9563-f8375c3043ce
        userCondition: null
fields:
  5f37a37b-d287-46e1-ab4c-0b7f707fa5ab: # Image Link
    columnSuffix: tbglnxgr
    contentColumnType: text
    fieldGroup: null
    handle: imagelink
    instructions: null
    name: 'Image Link'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: imahesLinks
name: 'imahes links'
sortOrder: 1
