fieldLayouts:
  2b2dbc3f-adc8-434c-b80e-fa7fabb3ff10:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 960c8a9c-3c13-472a-8088-ce59b16af267
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 128e390f-1f95-498c-955e-02e70d71075d
        userCondition: null
fs: fonts
handle: fonts
name: Fonts
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: fonts
transformSubpath: ''
