columnSuffix: slikstim
contentColumnType: datetime
fieldGroup: d8d4af19-ec79-4aaf-a8dd-ee46154d05e0 # Applications
handle: akhrThdyth
instructions: null
name: "آخر تحديث\t"
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
  showDate: true
  showTime: false
  showTimeZone: false
translationKeyFormat: null
translationMethod: site
type: craft\fields\Date
