columnSuffix: edfgcuvk
contentColumnType: 'decimal(12,2)'
fieldGroup: d8d4af19-ec79-4aaf-a8dd-ee46154d05e0 # Applications
handle: appPrice
instructions: null
name: 'App Price'
searchable: false
settings:
  decimals: 2
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Number
