columnSuffix: null
contentColumnType: string
fieldGroup: d8d4af19-ec79-4aaf-a8dd-ee46154d05e0 # Applications
handle: appRelatedEntries
instructions: null
name: 'App Related Entries'
searchable: false
settings:
  contentTable: '{{%matrixcontent_apprelatedentries}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: none
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
