columnSuffix: null
contentColumnType: string
fieldGroup: 5b2622ea-6477-40f1-ae8b-a6e0feac8329 # Articles
handle: articleCategory
instructions: null
name: 'Article Category'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: true
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  sources:
    - 'section:articlesCategories'
  targetSiteId: null
  validateRelatedElements: true
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
