columnSuffix: null
contentColumnType: string
fieldGroup: 039db95e-99b1-4a38-b655-0ae4de98723d # Global
handle: footerNavigation
instructions: null
name: 'Footer Navigation'
searchable: false
settings:
  blockTypeFields: 0
  changedFieldIndicator: 794473788
  contentTable: '{{%stc_footernavigation}}'
  fieldLayout: matrix
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: none
  selectionLabel: null
  staticField: null
translationKeyFormat: null
translationMethod: none
type: verbb\supertable\fields\SuperTableField
