columnSuffix: tswlfixw
contentColumnType: text
fieldGroup: 039db95e-99b1-4a38-b655-0ae4de98723d # Global
handle: googleVerificationCode
instructions: null
name: 'Google Verification Code'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
