columnSuffix: tmnenhmc
contentColumnType: boolean
fieldGroup: d8d4af19-ec79-4aaf-a8dd-ee46154d05e0 # Applications
handle: hasFaqs
instructions: null
name: 'Has Faqs'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Lightswitch
