columnSuffix: eloiywfa
contentColumnType: boolean
fieldGroup: d8d4af19-ec79-4aaf-a8dd-ee46154d05e0 # Applications
handle: imagesFromCdn
instructions: null
name: 'images From Cdn'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
