columnSuffix: hnkabicf
contentColumnType: char(7)
fieldGroup: d8d4af19-ec79-4aaf-a8dd-ee46154d05e0 # Applications
handle: lonKhtArticle
instructions: null
name: 'لون خط article'
searchable: false
settings:
  defaultColor: '#000000'
translationKeyFormat: null
translationMethod: site
type: craft\fields\Color
