columnSuffix: nlhgoehc
contentColumnType: char(7)
fieldGroup: d8d4af19-ec79-4aaf-a8dd-ee46154d05e0 # Applications
handle: lonKhtAlhydr
instructions: null
name: 'لون خط الهيدر'
searchable: false
settings:
  defaultColor: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Color
