columnSuffix: fcduzxkw
contentColumnType: integer(10)
fieldGroup: d8d4af19-ec79-4aaf-a8dd-ee46154d05e0 # Applications
handle: oldAppRatingCount
instructions: null
name: 'old app Rating Count'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: none
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Number
