columnSuffix: null
contentColumnType: string
fieldGroup: 039db95e-99b1-4a38-b655-0ae4de98723d # Global
handle: socialMediaLinks
instructions: null
name: 'Social Media Links'
searchable: false
settings:
  contentTable: '{{%matrixcontent_socialmedialinks}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: none
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
