columnSuffix: null
contentColumnType: string
fieldGroup: d8d4af19-ec79-4aaf-a8dd-ee46154d05e0 # Applications
handle: totalViews
instructions: null
name: 'Total Views'
searchable: false
settings:
  viewKey: null
translationKeyFormat: null
translationMethod: none
type: doublesecretagency\viewcount\fields\TotalViews
