changedFieldIndicator: 1157706701
field: 92c778ef-711b-4ec8-bb2c-76c2f9214aa7 # Quiz Table
fieldLayouts:
  32c616c1-a79d-4983-ab4c-253cd3837622:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 30894d92-6a1b-4011-9ef8-f009f7ae3b57 # Faq Answer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82fd57a6-b9d1-4948-8d9d-dce114a7c166
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ef7663bb-03ef-447b-91fb-1aede9487238 # Faq Quiz
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e82cc00d-27cc-42ba-9a3c-bead40f93156
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 06cb8b0a-694a-4080-903b-f57c4025e642
        userCondition: null
fields:
  30894d92-6a1b-4011-9ef8-f009f7ae3b57: # Faq Answer
    columnSuffix: xdqihbhl
    contentColumnType: text
    fieldGroup: null
    handle: faqAnswer
    instructions: null
    name: 'Faq Answer'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ef7663bb-03ef-447b-91fb-1aede9487238: # Faq Quiz
    columnSuffix: swcrqzhy
    contentColumnType: text
    fieldGroup: null
    handle: faqQuiz
    instructions: null
    name: 'Faq Quiz'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
